# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/menglaijun/octo-whale/build/example

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/menglaijun/octo-whale/build/example

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/menglaijun/octo-whale/build/example/CMakeFiles /opt/menglaijun/octo-whale/build/example/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/menglaijun/octo-whale/build/example/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named auth_example

# Build rule for target.
auth_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auth_example
.PHONY : auth_example

# fast build rule for target.
auth_example/fast:
	$(MAKE) -f CMakeFiles/auth_example.dir/build.make CMakeFiles/auth_example.dir/build
.PHONY : auth_example/fast

#=============================================================================
# Target rules for targets named cthrift_async_example

# Build rule for target.
cthrift_async_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_async_example
.PHONY : cthrift_async_example

# fast build rule for target.
cthrift_async_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/build
.PHONY : cthrift_async_example/fast

#=============================================================================
# Target rules for targets named cthrift_cli_auth_example

# Build rule for target.
cthrift_cli_auth_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_cli_auth_example
.PHONY : cthrift_cli_auth_example

# fast build rule for target.
cthrift_cli_auth_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/build
.PHONY : cthrift_cli_auth_example/fast

#=============================================================================
# Target rules for targets named cthrift_cli_example

# Build rule for target.
cthrift_cli_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_cli_example
.PHONY : cthrift_cli_example

# fast build rule for target.
cthrift_cli_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/build
.PHONY : cthrift_cli_example/fast

#=============================================================================
# Target rules for targets named cthrift_cli_example_mesh

# Build rule for target.
cthrift_cli_example_mesh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_cli_example_mesh
.PHONY : cthrift_cli_example_mesh

# fast build rule for target.
cthrift_cli_example_mesh/fast:
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/build
.PHONY : cthrift_cli_example_mesh/fast

#=============================================================================
# Target rules for targets named cthrift_cli_ipport_example

# Build rule for target.
cthrift_cli_ipport_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_cli_ipport_example
.PHONY : cthrift_cli_ipport_example

# fast build rule for target.
cthrift_cli_ipport_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/build
.PHONY : cthrift_cli_ipport_example/fast

#=============================================================================
# Target rules for targets named cthrift_cli_tags_example

# Build rule for target.
cthrift_cli_tags_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_cli_tags_example
.PHONY : cthrift_cli_tags_example

# fast build rule for target.
cthrift_cli_tags_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/build
.PHONY : cthrift_cli_tags_example/fast

#=============================================================================
# Target rules for targets named cthrift_pb_cli_example

# Build rule for target.
cthrift_pb_cli_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_pb_cli_example
.PHONY : cthrift_pb_cli_example

# fast build rule for target.
cthrift_pb_cli_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/build
.PHONY : cthrift_pb_cli_example/fast

#=============================================================================
# Target rules for targets named cthrift_svr_async_example

# Build rule for target.
cthrift_svr_async_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_svr_async_example
.PHONY : cthrift_svr_async_example

# fast build rule for target.
cthrift_svr_async_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/build
.PHONY : cthrift_svr_async_example/fast

#=============================================================================
# Target rules for targets named cthrift_svr_auth_example

# Build rule for target.
cthrift_svr_auth_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_svr_auth_example
.PHONY : cthrift_svr_auth_example

# fast build rule for target.
cthrift_svr_auth_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/build
.PHONY : cthrift_svr_auth_example/fast

#=============================================================================
# Target rules for targets named cthrift_svr_example

# Build rule for target.
cthrift_svr_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_svr_example
.PHONY : cthrift_svr_example

# fast build rule for target.
cthrift_svr_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/build
.PHONY : cthrift_svr_example/fast

#=============================================================================
# Target rules for targets named cthrift_svr_example_mesh

# Build rule for target.
cthrift_svr_example_mesh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_svr_example_mesh
.PHONY : cthrift_svr_example_mesh

# fast build rule for target.
cthrift_svr_example_mesh/fast:
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/build
.PHONY : cthrift_svr_example_mesh/fast

#=============================================================================
# Target rules for targets named cthrift_svr_pb_example

# Build rule for target.
cthrift_svr_pb_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_svr_pb_example
.PHONY : cthrift_svr_pb_example

# fast build rule for target.
cthrift_svr_pb_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/build
.PHONY : cthrift_svr_pb_example/fast

#=============================================================================
# Target rules for targets named cthrift_svr_tags_example

# Build rule for target.
cthrift_svr_tags_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cthrift_svr_tags_example
.PHONY : cthrift_svr_tags_example

# fast build rule for target.
cthrift_svr_tags_example/fast:
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/build
.PHONY : cthrift_svr_tags_example/fast

#=============================================================================
# Target rules for targets named kms_example

# Build rule for target.
kms_example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kms_example
.PHONY : kms_example

# fast build rule for target.
kms_example/fast:
	$(MAKE) -f CMakeFiles/kms_example.dir/build.make CMakeFiles/kms_example.dir/build
.PHONY : kms_example/fast

auth_example.o: auth_example.cc.o
.PHONY : auth_example.o

# target to build an object file
auth_example.cc.o:
	$(MAKE) -f CMakeFiles/auth_example.dir/build.make CMakeFiles/auth_example.dir/auth_example.cc.o
.PHONY : auth_example.cc.o

auth_example.i: auth_example.cc.i
.PHONY : auth_example.i

# target to preprocess a source file
auth_example.cc.i:
	$(MAKE) -f CMakeFiles/auth_example.dir/build.make CMakeFiles/auth_example.dir/auth_example.cc.i
.PHONY : auth_example.cc.i

auth_example.s: auth_example.cc.s
.PHONY : auth_example.s

# target to generate assembly for a file
auth_example.cc.s:
	$(MAKE) -f CMakeFiles/auth_example.dir/build.make CMakeFiles/auth_example.dir/auth_example.cc.s
.PHONY : auth_example.cc.s

cthrift_async_example.o: cthrift_async_example.cc.o
.PHONY : cthrift_async_example.o

# target to build an object file
cthrift_async_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/cthrift_async_example.cc.o
.PHONY : cthrift_async_example.cc.o

cthrift_async_example.i: cthrift_async_example.cc.i
.PHONY : cthrift_async_example.i

# target to preprocess a source file
cthrift_async_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/cthrift_async_example.cc.i
.PHONY : cthrift_async_example.cc.i

cthrift_async_example.s: cthrift_async_example.cc.s
.PHONY : cthrift_async_example.s

# target to generate assembly for a file
cthrift_async_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/cthrift_async_example.cc.s
.PHONY : cthrift_async_example.cc.s

cthrift_cli_auth_example.o: cthrift_cli_auth_example.cc.o
.PHONY : cthrift_cli_auth_example.o

# target to build an object file
cthrift_cli_auth_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/cthrift_cli_auth_example.cc.o
.PHONY : cthrift_cli_auth_example.cc.o

cthrift_cli_auth_example.i: cthrift_cli_auth_example.cc.i
.PHONY : cthrift_cli_auth_example.i

# target to preprocess a source file
cthrift_cli_auth_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/cthrift_cli_auth_example.cc.i
.PHONY : cthrift_cli_auth_example.cc.i

cthrift_cli_auth_example.s: cthrift_cli_auth_example.cc.s
.PHONY : cthrift_cli_auth_example.s

# target to generate assembly for a file
cthrift_cli_auth_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/cthrift_cli_auth_example.cc.s
.PHONY : cthrift_cli_auth_example.cc.s

cthrift_cli_example.o: cthrift_cli_example.cc.o
.PHONY : cthrift_cli_example.o

# target to build an object file
cthrift_cli_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/cthrift_cli_example.cc.o
.PHONY : cthrift_cli_example.cc.o

cthrift_cli_example.i: cthrift_cli_example.cc.i
.PHONY : cthrift_cli_example.i

# target to preprocess a source file
cthrift_cli_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/cthrift_cli_example.cc.i
.PHONY : cthrift_cli_example.cc.i

cthrift_cli_example.s: cthrift_cli_example.cc.s
.PHONY : cthrift_cli_example.s

# target to generate assembly for a file
cthrift_cli_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/cthrift_cli_example.cc.s
.PHONY : cthrift_cli_example.cc.s

cthrift_cli_example_mesh.o: cthrift_cli_example_mesh.cc.o
.PHONY : cthrift_cli_example_mesh.o

# target to build an object file
cthrift_cli_example_mesh.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/cthrift_cli_example_mesh.cc.o
.PHONY : cthrift_cli_example_mesh.cc.o

cthrift_cli_example_mesh.i: cthrift_cli_example_mesh.cc.i
.PHONY : cthrift_cli_example_mesh.i

# target to preprocess a source file
cthrift_cli_example_mesh.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/cthrift_cli_example_mesh.cc.i
.PHONY : cthrift_cli_example_mesh.cc.i

cthrift_cli_example_mesh.s: cthrift_cli_example_mesh.cc.s
.PHONY : cthrift_cli_example_mesh.s

# target to generate assembly for a file
cthrift_cli_example_mesh.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/cthrift_cli_example_mesh.cc.s
.PHONY : cthrift_cli_example_mesh.cc.s

cthrift_cli_ipport_example.o: cthrift_cli_ipport_example.cc.o
.PHONY : cthrift_cli_ipport_example.o

# target to build an object file
cthrift_cli_ipport_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/cthrift_cli_ipport_example.cc.o
.PHONY : cthrift_cli_ipport_example.cc.o

cthrift_cli_ipport_example.i: cthrift_cli_ipport_example.cc.i
.PHONY : cthrift_cli_ipport_example.i

# target to preprocess a source file
cthrift_cli_ipport_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/cthrift_cli_ipport_example.cc.i
.PHONY : cthrift_cli_ipport_example.cc.i

cthrift_cli_ipport_example.s: cthrift_cli_ipport_example.cc.s
.PHONY : cthrift_cli_ipport_example.s

# target to generate assembly for a file
cthrift_cli_ipport_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/cthrift_cli_ipport_example.cc.s
.PHONY : cthrift_cli_ipport_example.cc.s

cthrift_cli_tags_example.o: cthrift_cli_tags_example.cc.o
.PHONY : cthrift_cli_tags_example.o

# target to build an object file
cthrift_cli_tags_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/cthrift_cli_tags_example.cc.o
.PHONY : cthrift_cli_tags_example.cc.o

cthrift_cli_tags_example.i: cthrift_cli_tags_example.cc.i
.PHONY : cthrift_cli_tags_example.i

# target to preprocess a source file
cthrift_cli_tags_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/cthrift_cli_tags_example.cc.i
.PHONY : cthrift_cli_tags_example.cc.i

cthrift_cli_tags_example.s: cthrift_cli_tags_example.cc.s
.PHONY : cthrift_cli_tags_example.s

# target to generate assembly for a file
cthrift_cli_tags_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/cthrift_cli_tags_example.cc.s
.PHONY : cthrift_cli_tags_example.cc.s

cthrift_pb_cli_example.o: cthrift_pb_cli_example.cc.o
.PHONY : cthrift_pb_cli_example.o

# target to build an object file
cthrift_pb_cli_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/cthrift_pb_cli_example.cc.o
.PHONY : cthrift_pb_cli_example.cc.o

cthrift_pb_cli_example.i: cthrift_pb_cli_example.cc.i
.PHONY : cthrift_pb_cli_example.i

# target to preprocess a source file
cthrift_pb_cli_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/cthrift_pb_cli_example.cc.i
.PHONY : cthrift_pb_cli_example.cc.i

cthrift_pb_cli_example.s: cthrift_pb_cli_example.cc.s
.PHONY : cthrift_pb_cli_example.s

# target to generate assembly for a file
cthrift_pb_cli_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/cthrift_pb_cli_example.cc.s
.PHONY : cthrift_pb_cli_example.cc.s

cthrift_svr_async_example.o: cthrift_svr_async_example.cc.o
.PHONY : cthrift_svr_async_example.o

# target to build an object file
cthrift_svr_async_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/cthrift_svr_async_example.cc.o
.PHONY : cthrift_svr_async_example.cc.o

cthrift_svr_async_example.i: cthrift_svr_async_example.cc.i
.PHONY : cthrift_svr_async_example.i

# target to preprocess a source file
cthrift_svr_async_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/cthrift_svr_async_example.cc.i
.PHONY : cthrift_svr_async_example.cc.i

cthrift_svr_async_example.s: cthrift_svr_async_example.cc.s
.PHONY : cthrift_svr_async_example.s

# target to generate assembly for a file
cthrift_svr_async_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/cthrift_svr_async_example.cc.s
.PHONY : cthrift_svr_async_example.cc.s

cthrift_svr_auth_example.o: cthrift_svr_auth_example.cc.o
.PHONY : cthrift_svr_auth_example.o

# target to build an object file
cthrift_svr_auth_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/cthrift_svr_auth_example.cc.o
.PHONY : cthrift_svr_auth_example.cc.o

cthrift_svr_auth_example.i: cthrift_svr_auth_example.cc.i
.PHONY : cthrift_svr_auth_example.i

# target to preprocess a source file
cthrift_svr_auth_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/cthrift_svr_auth_example.cc.i
.PHONY : cthrift_svr_auth_example.cc.i

cthrift_svr_auth_example.s: cthrift_svr_auth_example.cc.s
.PHONY : cthrift_svr_auth_example.s

# target to generate assembly for a file
cthrift_svr_auth_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/cthrift_svr_auth_example.cc.s
.PHONY : cthrift_svr_auth_example.cc.s

cthrift_svr_example.o: cthrift_svr_example.cc.o
.PHONY : cthrift_svr_example.o

# target to build an object file
cthrift_svr_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/cthrift_svr_example.cc.o
.PHONY : cthrift_svr_example.cc.o

cthrift_svr_example.i: cthrift_svr_example.cc.i
.PHONY : cthrift_svr_example.i

# target to preprocess a source file
cthrift_svr_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/cthrift_svr_example.cc.i
.PHONY : cthrift_svr_example.cc.i

cthrift_svr_example.s: cthrift_svr_example.cc.s
.PHONY : cthrift_svr_example.s

# target to generate assembly for a file
cthrift_svr_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/cthrift_svr_example.cc.s
.PHONY : cthrift_svr_example.cc.s

cthrift_svr_example_mesh.o: cthrift_svr_example_mesh.cc.o
.PHONY : cthrift_svr_example_mesh.o

# target to build an object file
cthrift_svr_example_mesh.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/cthrift_svr_example_mesh.cc.o
.PHONY : cthrift_svr_example_mesh.cc.o

cthrift_svr_example_mesh.i: cthrift_svr_example_mesh.cc.i
.PHONY : cthrift_svr_example_mesh.i

# target to preprocess a source file
cthrift_svr_example_mesh.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/cthrift_svr_example_mesh.cc.i
.PHONY : cthrift_svr_example_mesh.cc.i

cthrift_svr_example_mesh.s: cthrift_svr_example_mesh.cc.s
.PHONY : cthrift_svr_example_mesh.s

# target to generate assembly for a file
cthrift_svr_example_mesh.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/cthrift_svr_example_mesh.cc.s
.PHONY : cthrift_svr_example_mesh.cc.s

cthrift_svr_pb_example.o: cthrift_svr_pb_example.cc.o
.PHONY : cthrift_svr_pb_example.o

# target to build an object file
cthrift_svr_pb_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/cthrift_svr_pb_example.cc.o
.PHONY : cthrift_svr_pb_example.cc.o

cthrift_svr_pb_example.i: cthrift_svr_pb_example.cc.i
.PHONY : cthrift_svr_pb_example.i

# target to preprocess a source file
cthrift_svr_pb_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/cthrift_svr_pb_example.cc.i
.PHONY : cthrift_svr_pb_example.cc.i

cthrift_svr_pb_example.s: cthrift_svr_pb_example.cc.s
.PHONY : cthrift_svr_pb_example.s

# target to generate assembly for a file
cthrift_svr_pb_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/cthrift_svr_pb_example.cc.s
.PHONY : cthrift_svr_pb_example.cc.s

cthrift_svr_tags_example.o: cthrift_svr_tags_example.cc.o
.PHONY : cthrift_svr_tags_example.o

# target to build an object file
cthrift_svr_tags_example.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/cthrift_svr_tags_example.cc.o
.PHONY : cthrift_svr_tags_example.cc.o

cthrift_svr_tags_example.i: cthrift_svr_tags_example.cc.i
.PHONY : cthrift_svr_tags_example.i

# target to preprocess a source file
cthrift_svr_tags_example.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/cthrift_svr_tags_example.cc.i
.PHONY : cthrift_svr_tags_example.cc.i

cthrift_svr_tags_example.s: cthrift_svr_tags_example.cc.s
.PHONY : cthrift_svr_tags_example.s

# target to generate assembly for a file
cthrift_svr_tags_example.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/cthrift_svr_tags_example.cc.s
.PHONY : cthrift_svr_tags_example.cc.s

echo.pb.o: echo.pb.cc.o
.PHONY : echo.pb.o

# target to build an object file
echo.pb.cc.o:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/echo.pb.cc.o
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/echo.pb.cc.o
.PHONY : echo.pb.cc.o

echo.pb.i: echo.pb.cc.i
.PHONY : echo.pb.i

# target to preprocess a source file
echo.pb.cc.i:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/echo.pb.cc.i
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/echo.pb.cc.i
.PHONY : echo.pb.cc.i

echo.pb.s: echo.pb.cc.s
.PHONY : echo.pb.s

# target to generate assembly for a file
echo.pb.cc.s:
	$(MAKE) -f CMakeFiles/cthrift_pb_cli_example.dir/build.make CMakeFiles/cthrift_pb_cli_example.dir/echo.pb.cc.s
	$(MAKE) -f CMakeFiles/cthrift_svr_pb_example.dir/build.make CMakeFiles/cthrift_svr_pb_example.dir/echo.pb.cc.s
.PHONY : echo.pb.cc.s

echo/Echo.o: echo/Echo.cpp.o
.PHONY : echo/Echo.o

# target to build an object file
echo/Echo.cpp.o:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/Echo.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/Echo.cpp.o
.PHONY : echo/Echo.cpp.o

echo/Echo.i: echo/Echo.cpp.i
.PHONY : echo/Echo.i

# target to preprocess a source file
echo/Echo.cpp.i:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/Echo.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/Echo.cpp.i
.PHONY : echo/Echo.cpp.i

echo/Echo.s: echo/Echo.cpp.s
.PHONY : echo/Echo.s

# target to generate assembly for a file
echo/Echo.cpp.s:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/Echo.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/Echo.cpp.s
.PHONY : echo/Echo.cpp.s

echo/echo_constants.o: echo/echo_constants.cpp.o
.PHONY : echo/echo_constants.o

# target to build an object file
echo/echo_constants.cpp.o:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/echo_constants.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/echo_constants.cpp.o
.PHONY : echo/echo_constants.cpp.o

echo/echo_constants.i: echo/echo_constants.cpp.i
.PHONY : echo/echo_constants.i

# target to preprocess a source file
echo/echo_constants.cpp.i:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/echo_constants.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/echo_constants.cpp.i
.PHONY : echo/echo_constants.cpp.i

echo/echo_constants.s: echo/echo_constants.cpp.s
.PHONY : echo/echo_constants.s

# target to generate assembly for a file
echo/echo_constants.cpp.s:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/echo_constants.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/echo_constants.cpp.s
.PHONY : echo/echo_constants.cpp.s

echo/echo_types.o: echo/echo_types.cpp.o
.PHONY : echo/echo_types.o

# target to build an object file
echo/echo_types.cpp.o:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/echo_types.cpp.o
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/echo_types.cpp.o
.PHONY : echo/echo_types.cpp.o

echo/echo_types.i: echo/echo_types.cpp.i
.PHONY : echo/echo_types.i

# target to preprocess a source file
echo/echo_types.cpp.i:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/echo_types.cpp.i
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/echo_types.cpp.i
.PHONY : echo/echo_types.cpp.i

echo/echo_types.s: echo/echo_types.cpp.s
.PHONY : echo/echo_types.s

# target to generate assembly for a file
echo/echo_types.cpp.s:
	$(MAKE) -f CMakeFiles/cthrift_async_example.dir/build.make CMakeFiles/cthrift_async_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_auth_example.dir/build.make CMakeFiles/cthrift_cli_auth_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_example.dir/build.make CMakeFiles/cthrift_cli_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_example_mesh.dir/build.make CMakeFiles/cthrift_cli_example_mesh.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_ipport_example.dir/build.make CMakeFiles/cthrift_cli_ipport_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_cli_tags_example.dir/build.make CMakeFiles/cthrift_cli_tags_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_async_example.dir/build.make CMakeFiles/cthrift_svr_async_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_auth_example.dir/build.make CMakeFiles/cthrift_svr_auth_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_example.dir/build.make CMakeFiles/cthrift_svr_example.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_example_mesh.dir/build.make CMakeFiles/cthrift_svr_example_mesh.dir/echo/echo_types.cpp.s
	$(MAKE) -f CMakeFiles/cthrift_svr_tags_example.dir/build.make CMakeFiles/cthrift_svr_tags_example.dir/echo/echo_types.cpp.s
.PHONY : echo/echo_types.cpp.s

kms_example.o: kms_example.cc.o
.PHONY : kms_example.o

# target to build an object file
kms_example.cc.o:
	$(MAKE) -f CMakeFiles/kms_example.dir/build.make CMakeFiles/kms_example.dir/kms_example.cc.o
.PHONY : kms_example.cc.o

kms_example.i: kms_example.cc.i
.PHONY : kms_example.i

# target to preprocess a source file
kms_example.cc.i:
	$(MAKE) -f CMakeFiles/kms_example.dir/build.make CMakeFiles/kms_example.dir/kms_example.cc.i
.PHONY : kms_example.cc.i

kms_example.s: kms_example.cc.s
.PHONY : kms_example.s

# target to generate assembly for a file
kms_example.cc.s:
	$(MAKE) -f CMakeFiles/kms_example.dir/build.make CMakeFiles/kms_example.dir/kms_example.cc.s
.PHONY : kms_example.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... auth_example"
	@echo "... cthrift_async_example"
	@echo "... cthrift_cli_auth_example"
	@echo "... cthrift_cli_example"
	@echo "... cthrift_cli_example_mesh"
	@echo "... cthrift_cli_ipport_example"
	@echo "... cthrift_cli_tags_example"
	@echo "... cthrift_pb_cli_example"
	@echo "... cthrift_svr_async_example"
	@echo "... cthrift_svr_auth_example"
	@echo "... cthrift_svr_example"
	@echo "... cthrift_svr_example_mesh"
	@echo "... cthrift_svr_pb_example"
	@echo "... cthrift_svr_tags_example"
	@echo "... edit_cache"
	@echo "... kms_example"
	@echo "... rebuild_cache"
	@echo "... auth_example.o"
	@echo "... auth_example.i"
	@echo "... auth_example.s"
	@echo "... cthrift_async_example.o"
	@echo "... cthrift_async_example.i"
	@echo "... cthrift_async_example.s"
	@echo "... cthrift_cli_auth_example.o"
	@echo "... cthrift_cli_auth_example.i"
	@echo "... cthrift_cli_auth_example.s"
	@echo "... cthrift_cli_example.o"
	@echo "... cthrift_cli_example.i"
	@echo "... cthrift_cli_example.s"
	@echo "... cthrift_cli_example_mesh.o"
	@echo "... cthrift_cli_example_mesh.i"
	@echo "... cthrift_cli_example_mesh.s"
	@echo "... cthrift_cli_ipport_example.o"
	@echo "... cthrift_cli_ipport_example.i"
	@echo "... cthrift_cli_ipport_example.s"
	@echo "... cthrift_cli_tags_example.o"
	@echo "... cthrift_cli_tags_example.i"
	@echo "... cthrift_cli_tags_example.s"
	@echo "... cthrift_pb_cli_example.o"
	@echo "... cthrift_pb_cli_example.i"
	@echo "... cthrift_pb_cli_example.s"
	@echo "... cthrift_svr_async_example.o"
	@echo "... cthrift_svr_async_example.i"
	@echo "... cthrift_svr_async_example.s"
	@echo "... cthrift_svr_auth_example.o"
	@echo "... cthrift_svr_auth_example.i"
	@echo "... cthrift_svr_auth_example.s"
	@echo "... cthrift_svr_example.o"
	@echo "... cthrift_svr_example.i"
	@echo "... cthrift_svr_example.s"
	@echo "... cthrift_svr_example_mesh.o"
	@echo "... cthrift_svr_example_mesh.i"
	@echo "... cthrift_svr_example_mesh.s"
	@echo "... cthrift_svr_pb_example.o"
	@echo "... cthrift_svr_pb_example.i"
	@echo "... cthrift_svr_pb_example.s"
	@echo "... cthrift_svr_tags_example.o"
	@echo "... cthrift_svr_tags_example.i"
	@echo "... cthrift_svr_tags_example.s"
	@echo "... echo.pb.o"
	@echo "... echo.pb.i"
	@echo "... echo.pb.s"
	@echo "... echo/Echo.o"
	@echo "... echo/Echo.i"
	@echo "... echo/Echo.s"
	@echo "... echo/echo_constants.o"
	@echo "... echo/echo_constants.i"
	@echo "... echo/echo_constants.s"
	@echo "... echo/echo_types.o"
	@echo "... echo/echo_types.i"
	@echo "... echo/echo_types.s"
	@echo "... kms_example.o"
	@echo "... kms_example.i"
	@echo "... kms_example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

